// GENERATED by scripts/gen-pq-schema.mjs from the backend Ecto schemas —
// do not edit. Regenerate after a backend schema change:
//   node scripts/gen-pq-schema.mjs

export type FieldType = 'text' | 'int' | 'bool' | 'binary' | 'binary[]';

/** Column name → type. sign_b64 and sign_hash are never signable. */
export type SignableSchema = Record<string, FieldType>;

export const SIGNABLE: Record<string, SignableSchema> = {
	user_cards: {
		user_hash: 'text',
		sign_pkey: 'binary',
		contact_pkey: 'binary',
		contact_cert: 'binary',
		crypt_pkey: 'binary',
		crypt_cert: 'binary',
		name: 'text',
		deleted_flag: 'bool',
		owner_timestamp: 'int',
	},
	user_storage: {
		user_hash: 'text',
		uuid: 'text',
		value_b64: 'binary',
		deleted_flag: 'bool',
		parent_sign_hash: 'text',
		owner_timestamp: 'int',
	},
	dialog_keys: {
		dialog_hash: 'text',
		sender_hash: 'text',
		peer_hash: 'text',
		peer_kem_wrap_key_b64: 'binary',
		peer_wrapped_msg_key_b64: 'binary',
		owner_timestamp: 'int',
		deleted_flag: 'bool',
	},
	dialog_messages: {
		message_id: 'text',
		dialog_hash: 'text',
		sender_hash: 'text',
		content_b64: 'binary',
		deleted_flag: 'bool',
		refs_map_b64: 'binary',
		parent_sign_hash: 'text',
		owner_timestamp: 'int',
	},
	dialog_messages_versions: {
		message_id: 'text',
		dialog_hash: 'text',
		sender_hash: 'text',
		content_b64: 'binary',
		deleted_flag: 'bool',
		refs_map_b64: 'binary',
		parent_sign_hash: 'text',
		owner_timestamp: 'int',
	},
	dialog_message_reactions: {
		reaction_hash: 'text',
		dialog_hash: 'text',
		message_id: 'text',
		message_sign_hash: 'text',
		reactor_hash: 'text',
		type_b64: 'binary',
		deleted_flag: 'bool',
		owner_timestamp: 'int',
	},
	dialog_message_receipts: {
		receipt_hash: 'text',
		dialog_hash: 'text',
		message_id: 'text',
		peer_hash: 'text',
		type: 'text',
		message_sign_hash: 'text',
		owner_timestamp: 'int',
	},
	files: {
		file_id: 'text',
		uploader_hash: 'text',
		total_size: 'int',
		chunk_size: 'int',
		chunk_count: 'int',
		chunk_sign_hashes: 'binary[]',
		owner_timestamp: 'int',
		deleted_flag: 'bool',
	},
};
